use super::*;

/// See [enums module](super) documentation.
///
/// Hand-written (not generated by the `strategy_enum_impl!` macro used in this
/// module's parent, unlike `Strategy1D`/`2D`/`3DEnum<T>`) and **not** generic over a
/// grid/value type at all: every built-in ND strategy either does no arithmetic at
/// all (`Nearest`, `Step`, genuinely `Dg`/`Dv`-independent) or works in the shared
/// `f64` blend precision (`Linear`, `LinearUniform`, `CubicC2`, `GridTransform`,
/// `ValuesTransform`, see [`StrategyND`]'s docs), so nothing stored here is actually
/// `Tg`- or `Tv`-typed.
/// `impl<Dg, Dv> StrategyND<Dg, Dv> for StrategyNDEnum` below is a blanket impl over
/// every `Dg`/`Dv` pair meeting the bound, rather than one type per instantiation.
#[allow(missing_docs)]
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(Deserialize, Serialize))]
#[cfg_attr(feature = "serde", serde(untagged))]
#[non_exhaustive]
pub enum StrategyNDEnum {
    Nearest(strategy::Nearest),
    Step(strategy::Step),
    Linear(strategy::Linear),
    LinearUniform(strategy::LinearUniform),
    CubicC2(strategy::CubicC2<f64>),
    GridTransform(strategy::GridTransform<f64, Box<StrategyNDEnum>>),
    ValuesTransform(strategy::ValuesTransform<f64, Box<StrategyNDEnum>>),
}

impl From<strategy::Nearest> for StrategyNDEnum {
    #[inline]
    fn from(strategy: strategy::Nearest) -> Self {
        Self::Nearest(strategy)
    }
}
impl From<strategy::Step> for StrategyNDEnum {
    #[inline]
    fn from(strategy: strategy::Step) -> Self {
        Self::Step(strategy)
    }
}
impl From<strategy::Linear> for StrategyNDEnum {
    #[inline]
    fn from(strategy: strategy::Linear) -> Self {
        Self::Linear(strategy)
    }
}
impl From<strategy::LinearUniform> for StrategyNDEnum {
    #[inline]
    fn from(strategy: strategy::LinearUniform) -> Self {
        Self::LinearUniform(strategy)
    }
}
impl From<strategy::CubicC2<f64>> for StrategyNDEnum {
    #[inline]
    fn from(strategy: strategy::CubicC2<f64>) -> Self {
        Self::CubicC2(strategy)
    }
}
impl From<strategy::GridTransform<f64, Box<StrategyNDEnum>>> for StrategyNDEnum {
    #[inline]
    fn from(strategy: strategy::GridTransform<f64, Box<StrategyNDEnum>>) -> Self {
        Self::GridTransform(strategy)
    }
}
impl From<strategy::ValuesTransform<f64, Box<StrategyNDEnum>>> for StrategyNDEnum {
    #[inline]
    fn from(strategy: strategy::ValuesTransform<f64, Box<StrategyNDEnum>>) -> Self {
        Self::ValuesTransform(strategy)
    }
}

impl<Dg, Dv> StrategyND<Dg, Dv> for StrategyNDEnum
where
    Dg: Data + RawDataClone + Clone,
    Dg::Elem: PartialEq + Debug + NumCast + PartialOrd + Copy,
    Dv: Data + RawDataClone + Clone,
    Dv::Elem: PartialEq + Debug + NumCast + Copy,
{
    #[inline]
    fn validate(&self, data: &InterpDataNDBase<Dg, Dv>) -> Result<(), ValidateError> {
        match self {
            Self::Nearest(s) => StrategyND::<Dg, Dv>::validate(s, data),
            Self::Step(s) => StrategyND::<Dg, Dv>::validate(s, data),
            Self::Linear(s) => StrategyND::<Dg, Dv>::validate(s, data),
            Self::LinearUniform(s) => StrategyND::<Dg, Dv>::validate(s, data),
            Self::CubicC2(s) => StrategyND::<Dg, Dv>::validate(s, data),
            Self::GridTransform(s) => StrategyND::<Dg, Dv>::validate(s, data),
            Self::ValuesTransform(s) => StrategyND::<Dg, Dv>::validate(s, data),
        }
    }

    #[inline]
    fn init(&mut self, data: &InterpDataNDBase<Dg, Dv>) -> Result<(), ValidateError> {
        match self {
            Self::Nearest(s) => StrategyND::<Dg, Dv>::init(s, data),
            Self::Step(s) => StrategyND::<Dg, Dv>::init(s, data),
            Self::Linear(s) => StrategyND::<Dg, Dv>::init(s, data),
            Self::LinearUniform(s) => StrategyND::<Dg, Dv>::init(s, data),
            Self::CubicC2(s) => StrategyND::<Dg, Dv>::init(s, data),
            Self::GridTransform(s) => StrategyND::<Dg, Dv>::init(s, data),
            Self::ValuesTransform(s) => StrategyND::<Dg, Dv>::init(s, data),
        }
    }

    #[inline]
    fn interpolate(
        &self,
        data: &InterpDataNDBase<Dg, Dv>,
        point: &[f64],
    ) -> Result<Dv::Elem, InterpolateError> {
        match self {
            Self::Nearest(s) => StrategyND::<Dg, Dv>::interpolate(s, data, point),
            Self::Step(s) => StrategyND::<Dg, Dv>::interpolate(s, data, point),
            Self::Linear(s) => StrategyND::<Dg, Dv>::interpolate(s, data, point),
            Self::LinearUniform(s) => StrategyND::<Dg, Dv>::interpolate(s, data, point),
            Self::CubicC2(s) => StrategyND::<Dg, Dv>::interpolate(s, data, point),
            Self::GridTransform(s) => StrategyND::<Dg, Dv>::interpolate(s, data, point),
            Self::ValuesTransform(s) => StrategyND::<Dg, Dv>::interpolate(s, data, point),
        }
    }

    #[inline]
    fn interpolate_wrapped(
        &self,
        data: &InterpDataNDBase<Dg, Dv>,
        point: &[f64],
    ) -> Result<Dv::Elem, InterpolateError>
    where
        Dg::Elem: NumCast + Copy,
    {
        match self {
            Self::Nearest(s) => StrategyND::<Dg, Dv>::interpolate_wrapped(s, data, point),
            Self::Step(s) => StrategyND::<Dg, Dv>::interpolate_wrapped(s, data, point),
            Self::Linear(s) => StrategyND::<Dg, Dv>::interpolate_wrapped(s, data, point),
            Self::LinearUniform(s) => StrategyND::<Dg, Dv>::interpolate_wrapped(s, data, point),
            Self::CubicC2(s) => StrategyND::<Dg, Dv>::interpolate_wrapped(s, data, point),
            Self::GridTransform(s) => StrategyND::<Dg, Dv>::interpolate_wrapped(s, data, point),
            Self::ValuesTransform(s) => StrategyND::<Dg, Dv>::interpolate_wrapped(s, data, point),
        }
    }

    #[inline]
    fn interpolate_fast(&self, data: &InterpDataNDBase<Dg, Dv>, point: &[f64]) -> Dv::Elem {
        match self {
            Self::Nearest(s) => StrategyND::<Dg, Dv>::interpolate_fast(s, data, point),
            Self::Step(s) => StrategyND::<Dg, Dv>::interpolate_fast(s, data, point),
            Self::Linear(s) => StrategyND::<Dg, Dv>::interpolate_fast(s, data, point),
            Self::LinearUniform(s) => StrategyND::<Dg, Dv>::interpolate_fast(s, data, point),
            Self::CubicC2(s) => StrategyND::<Dg, Dv>::interpolate_fast(s, data, point),
            Self::GridTransform(s) => StrategyND::<Dg, Dv>::interpolate_fast(s, data, point),
            Self::ValuesTransform(s) => StrategyND::<Dg, Dv>::interpolate_fast(s, data, point),
        }
    }

    #[inline]
    fn batch_interpolate_into(
        &self,
        data: &InterpDataNDBase<Dg, Dv>,
        points: &[&[f64]],
        out: &mut [Dv::Elem],
    ) -> Result<(), InterpolateError> {
        match self {
            Self::Nearest(s) => StrategyND::<Dg, Dv>::batch_interpolate_into(s, data, points, out),
            Self::Step(s) => StrategyND::<Dg, Dv>::batch_interpolate_into(s, data, points, out),
            Self::Linear(s) => StrategyND::<Dg, Dv>::batch_interpolate_into(s, data, points, out),
            Self::LinearUniform(s) => {
                StrategyND::<Dg, Dv>::batch_interpolate_into(s, data, points, out)
            }
            Self::CubicC2(s) => StrategyND::<Dg, Dv>::batch_interpolate_into(s, data, points, out),
            Self::GridTransform(s) => {
                StrategyND::<Dg, Dv>::batch_interpolate_into(s, data, points, out)
            }
            Self::ValuesTransform(s) => {
                StrategyND::<Dg, Dv>::batch_interpolate_into(s, data, points, out)
            }
        }
    }

    #[inline]
    fn batch_interpolate_fast_into(
        &self,
        data: &InterpDataNDBase<Dg, Dv>,
        points: &[&[f64]],
        out: &mut [Dv::Elem],
    ) {
        match self {
            Self::Nearest(s) => {
                StrategyND::<Dg, Dv>::batch_interpolate_fast_into(s, data, points, out)
            }
            Self::Step(s) => {
                StrategyND::<Dg, Dv>::batch_interpolate_fast_into(s, data, points, out)
            }
            Self::Linear(s) => {
                StrategyND::<Dg, Dv>::batch_interpolate_fast_into(s, data, points, out)
            }
            Self::LinearUniform(s) => {
                StrategyND::<Dg, Dv>::batch_interpolate_fast_into(s, data, points, out)
            }
            Self::CubicC2(s) => {
                StrategyND::<Dg, Dv>::batch_interpolate_fast_into(s, data, points, out)
            }
            Self::GridTransform(s) => {
                StrategyND::<Dg, Dv>::batch_interpolate_fast_into(s, data, points, out)
            }
            Self::ValuesTransform(s) => {
                StrategyND::<Dg, Dv>::batch_interpolate_fast_into(s, data, points, out)
            }
        }
    }

    #[inline]
    fn batch_interpolate(
        &self,
        data: &InterpDataNDBase<Dg, Dv>,
        points: &[&[f64]],
    ) -> Result<Vec<Dv::Elem>, InterpolateError>
    where
        Dv::Elem: Num,
    {
        match self {
            Self::Nearest(s) => StrategyND::<Dg, Dv>::batch_interpolate(s, data, points),
            Self::Step(s) => StrategyND::<Dg, Dv>::batch_interpolate(s, data, points),
            Self::Linear(s) => StrategyND::<Dg, Dv>::batch_interpolate(s, data, points),
            Self::LinearUniform(s) => StrategyND::<Dg, Dv>::batch_interpolate(s, data, points),
            Self::CubicC2(s) => StrategyND::<Dg, Dv>::batch_interpolate(s, data, points),
            Self::GridTransform(s) => StrategyND::<Dg, Dv>::batch_interpolate(s, data, points),
            Self::ValuesTransform(s) => StrategyND::<Dg, Dv>::batch_interpolate(s, data, points),
        }
    }

    #[inline]
    fn batch_interpolate_fast(
        &self,
        data: &InterpDataNDBase<Dg, Dv>,
        points: &[&[f64]],
    ) -> Vec<Dv::Elem>
    where
        Dv::Elem: Num + Copy,
    {
        match self {
            Self::Nearest(s) => StrategyND::<Dg, Dv>::batch_interpolate_fast(s, data, points),
            Self::Step(s) => StrategyND::<Dg, Dv>::batch_interpolate_fast(s, data, points),
            Self::Linear(s) => StrategyND::<Dg, Dv>::batch_interpolate_fast(s, data, points),
            Self::LinearUniform(s) => StrategyND::<Dg, Dv>::batch_interpolate_fast(s, data, points),
            Self::CubicC2(s) => StrategyND::<Dg, Dv>::batch_interpolate_fast(s, data, points),
            Self::GridTransform(s) => StrategyND::<Dg, Dv>::batch_interpolate_fast(s, data, points),
            Self::ValuesTransform(s) => {
                StrategyND::<Dg, Dv>::batch_interpolate_fast(s, data, points)
            }
        }
    }

    #[inline]
    fn allow_extrapolate(&self) -> bool {
        match self {
            Self::Nearest(s) => StrategyND::<Dg, Dv>::allow_extrapolate(s),
            Self::Step(s) => StrategyND::<Dg, Dv>::allow_extrapolate(s),
            Self::Linear(s) => StrategyND::<Dg, Dv>::allow_extrapolate(s),
            Self::LinearUniform(s) => StrategyND::<Dg, Dv>::allow_extrapolate(s),
            Self::CubicC2(s) => StrategyND::<Dg, Dv>::allow_extrapolate(s),
            Self::GridTransform(s) => StrategyND::<Dg, Dv>::allow_extrapolate(s),
            Self::ValuesTransform(s) => StrategyND::<Dg, Dv>::allow_extrapolate(s),
        }
    }

    #[inline]
    fn check_batch_domain(&self, points: &[&[f64]]) -> Result<(), InterpolateError> {
        match self {
            Self::Nearest(s) => StrategyND::<Dg, Dv>::check_batch_domain(s, points),
            Self::Step(s) => StrategyND::<Dg, Dv>::check_batch_domain(s, points),
            Self::Linear(s) => StrategyND::<Dg, Dv>::check_batch_domain(s, points),
            Self::LinearUniform(s) => StrategyND::<Dg, Dv>::check_batch_domain(s, points),
            Self::CubicC2(s) => StrategyND::<Dg, Dv>::check_batch_domain(s, points),
            Self::GridTransform(s) => StrategyND::<Dg, Dv>::check_batch_domain(s, points),
            Self::ValuesTransform(s) => StrategyND::<Dg, Dv>::check_batch_domain(s, points),
        }
    }
}

/// See [enums module](super) documentation. `Box` here wraps the concrete enum (not
/// `dyn Trait`), breaking the infinite size a wrapper strategy's `inner: Self` field
/// would otherwise have if it named the enum directly (e.g. `GridTransform`'s
/// `inner`); serde's blanket `Box<T>` impl covers it, so unlike `Box<dyn Trait>` this
/// is fully serde-compatible.
impl<Dg, Dv> StrategyND<Dg, Dv> for Box<StrategyNDEnum>
where
    Dg: Data + RawDataClone + Clone,
    Dg::Elem: PartialEq + Debug + NumCast + PartialOrd + Copy,
    Dv: Data + RawDataClone + Clone,
    Dv::Elem: PartialEq + Debug + NumCast + Copy,
{
    #[inline]
    fn validate(&self, data: &InterpDataNDBase<Dg, Dv>) -> Result<(), ValidateError> {
        (**self).validate(data)
    }

    #[inline]
    fn init(&mut self, data: &InterpDataNDBase<Dg, Dv>) -> Result<(), ValidateError> {
        (**self).init(data)
    }

    #[inline]
    fn interpolate(
        &self,
        data: &InterpDataNDBase<Dg, Dv>,
        point: &[f64],
    ) -> Result<Dv::Elem, InterpolateError> {
        (**self).interpolate(data, point)
    }

    #[inline]
    fn interpolate_wrapped(
        &self,
        data: &InterpDataNDBase<Dg, Dv>,
        point: &[f64],
    ) -> Result<Dv::Elem, InterpolateError>
    where
        Dg::Elem: NumCast + Copy,
    {
        (**self).interpolate_wrapped(data, point)
    }

    #[inline]
    fn interpolate_fast(&self, data: &InterpDataNDBase<Dg, Dv>, point: &[f64]) -> Dv::Elem {
        (**self).interpolate_fast(data, point)
    }

    #[inline]
    fn batch_interpolate_into(
        &self,
        data: &InterpDataNDBase<Dg, Dv>,
        points: &[&[f64]],
        out: &mut [Dv::Elem],
    ) -> Result<(), InterpolateError> {
        (**self).batch_interpolate_into(data, points, out)
    }

    #[inline]
    fn batch_interpolate_fast_into(
        &self,
        data: &InterpDataNDBase<Dg, Dv>,
        points: &[&[f64]],
        out: &mut [Dv::Elem],
    ) {
        (**self).batch_interpolate_fast_into(data, points, out)
    }

    #[inline]
    fn batch_interpolate(
        &self,
        data: &InterpDataNDBase<Dg, Dv>,
        points: &[&[f64]],
    ) -> Result<Vec<Dv::Elem>, InterpolateError>
    where
        Dv::Elem: Num,
    {
        (**self).batch_interpolate(data, points)
    }

    #[inline]
    fn batch_interpolate_fast(
        &self,
        data: &InterpDataNDBase<Dg, Dv>,
        points: &[&[f64]],
    ) -> Vec<Dv::Elem>
    where
        Dv::Elem: Num + Copy,
    {
        (**self).batch_interpolate_fast(data, points)
    }

    #[inline]
    fn allow_extrapolate(&self) -> bool {
        StrategyND::<Dg, Dv>::allow_extrapolate(&**self)
    }

    #[inline]
    fn check_batch_domain(&self, points: &[&[f64]]) -> Result<(), InterpolateError> {
        StrategyND::<Dg, Dv>::check_batch_domain(&**self, points)
    }
}

#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    use super::*;

    #[test]
    #[cfg(feature = "serde")]
    fn test_serde() {
        assert_eq!(
            serde_json::to_string(&StrategyNDEnum::from(Linear)).unwrap(),
            serde_json::to_string(&Linear).unwrap(),
        );
        assert_eq!(
            serde_json::to_string(&StrategyNDEnum::from(Nearest)).unwrap(),
            serde_json::to_string(&Nearest).unwrap(),
        );
        assert_eq!(
            serde_json::to_string(&StrategyNDEnum::from(Step::from(
                strategy::step::StepDirection::Lower
            )))
            .unwrap(),
            serde_json::to_string(&Step::from(strategy::step::StepDirection::Lower)).unwrap(),
        );
        assert_eq!(
            serde_json::to_string(&StrategyNDEnum::from(CubicC2::<f64>::not_a_knot())).unwrap(),
            serde_json::to_string(&CubicC2::<f64>::not_a_knot()).unwrap(),
        );
    }
}
