name: release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cargo build --verbose
    - name: compile benchmarks
      run: cargo bench --no-run
    - name: test
      run: |
        cargo test --verbose
        cargo test --no-default-features --verbose
        cargo test --all-features --verbose
    # TODO: add this back when the cargo examples repo is more functional
    # - name: run examples
    #   run: |
    #     cargo install cargo-examples
    #     cargo examples
    - name: check semver
      uses: obi1kenobi/cargo-semver-checks-action@v2

  release:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4
    - run: cargo publish --dry-run
    - run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
