name: test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install cargo-hack
        uses: taiki-e/install-action@cargo-hack

      - name: check formatting
        run: cargo fmt --check

      - name: test
        # Note: this will be unwieldy if there are many features, but for now it is fine.
        run: cargo hack test --feature-powerset --verbose

      - name: run all examples
        run: |
          for name in $(cargo metadata --no-deps --format-version 1 | \
            python3 -c "import sys,json; [print(t['name']) for p in json.load(sys.stdin)['packages'] for t in p['targets'] if 'example' in t['kind']]"); do
            cargo run --example "$name"
          done

      - name: compile benchmarks
        run: cargo bench --no-run
